### ISSUE TITLE
Add rust files to watchFiles array

### ISSUE THREAD

**Issue by jasonwilliams** [Tschrock/esbuild-plugin-wasm-pack#1]
Currently when saving rust code ESBuild does not rebuild. ESBuild doesn't know about any rust files so is not watching them. 
It would be nice for this plugin to notify ESBuild of the Rust files in a project so they can also trigger builds https://esbuild.github.io/plugins/#resolve-results

A naïve approach might be to glob all .rs files inside the current directory (filtering out obvious directories). https://github.com/terkelg/tiny-glob could help with this

**Comment by Tschrock** [comment]
It looks like cargo will output a `*.d` file alongside build artifacts, listing the file dependencies (https://doc.rust-lang.org/cargo/guide/build-cache.html#dep-info-files). This will give a more accurate watch list (and it includes extra files from macros like `include_str` and `include_bytes`). I don't think it includes `build.rs` or `Cargo.toml` though, which could be useful. Also, cargo doesn't list this `.d` file in it's JSON build output - It's probably safe to assume it's in the same directory and using the same name as the final build artifact, but it would be good to fallback to `**/*.rs` in case it can't be found.

Of course, neither of these will catch newly created files, but I don't think esbuild can handle that anyway unless you watch the whole directory tree.

I'll schedule some time to work on this this weekend

**Comment by jasonwilliams** [comment]
Great investigation, thanks for looking into this, this will be such a huge usability improvement.

**Comment by jasonwilliams** [comment]
@Tschrock i saw you added some changes, let me know and I can test it

**Comment by Tschrock** [comment]
@jasonwilliams Sorry for the delay, I was having issues testing things and then got caught up in the holidays and job changes. I've merged in this feature and published a new version for it. If you encounter any problems with it please let me know.

**Comment by jasonwilliams** [comment]
@Tschrock it works great, thanks!
